### ISSUE TITLE
Get a select statemet instead of the qurey result.

### ISSUE THREAD

**Issue by dimazest** [Pylons/paginate_sqlalchemy#5]
Hi,

I've been wondering whether it would be possible to get the select statement on line [1] instead of the query result.

https://github.com/Pylons/paginate_sqlalchemy/blob/master/paginate_sqlalchemy/__init__.py#L52

**Comment by ergo** [comment]
You have the select statement already (since you pass it yourself), and you can easly figure out limit/offset parts if i understand your question correctly.
Do you have some special case that would require access to select object inside that wrapper?

**Comment by dimazest** [comment]
You are right, it's easier to figure out the offset and the limit manually than to change the code.

**Comment by ergo** [comment]
You can calculate limit offset by accessing page object properties like page and items_per_page, that data is available for you freely.
